fix: delete timazone setting

diff --git a/.github/workflows/Test_Build.yml b/.github/workflows/Test_Build.yml
--- a/.github/workflows/Test_Build.yml
+++ b/.github/workflows/Test_Build.yml
@@ -21,11 +21,6 @@ jobs:
     runs-on: macos-14
     steps:
     - uses: actions/checkout@v3
-    - uses: szenius/set-timezone@v1.1
-      with:
-        timezoneMacos: "Asia/Korea"
-      run:
-        listtimezones
     
     - name: Install pods
       run: |
@@ -37,17 +32,17 @@ jobs:
     - name: Select Xcode Version
       run: sudo xcode-select -s /Applications/Xcode_15.0.app
 
-    # - name: Run Test
-    #   run: |
-    #     xcodebuild build clean \
-    #     -workspace ./HANE24.xcworkspace \
-    #     -scheme 24HANE \
-    #     -destination 'platform=iOS Simulator,name=iPhone 14 Pro' \
-    #     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES test | xcpretty -c; echo "::set-output name=result::${PIPESTATUS[0]}"; echo "${PIPESTATUS[0]}"
+    - name: Run Test
+      run: |
+        xcodebuild build clean \
+        -workspace ./HANE24.xcworkspace \
+        -scheme 24HANE \
+        -destination 'platform=iOS Simulator,name=iPhone 14 Pro' \
+        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES test | xcpretty -c; echo "::set-output name=result::${PIPESTATUS[0]}"; echo "${PIPESTATUS[0]}"
     
-    # - name: Check Test Result
-    #   if: steps.logger_tests.outputs.result != 0
-    #   run: |
-    #     echo "Tests Failed"; exit 1
+    - name: Check Test Result
+      if: steps.logger_tests.outputs.result != 0
+      run: |
+        echo "Tests Failed"; exit 1
         
 
